# Generated by Django 4.2.7 on 2023-12-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ITEMID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=100)),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DESCRIPTION', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'menu_items',
                'managed': False,
            },
        ),
    ]
